### ISSUE TITLE
Stack creation times out

### ISSUE THREAD

**Issue by iconara** [burtcorp/cuffsert#4]
I tried setting up the same stack three times and each time it failed because creating an auto scaling group took too long (according to the CF console).

It was no problem creating the stack manually.

I got this error from the last run (don't remember if I got it on all the runs):

```
14:54:58+0000  AsgAsg[AWS::AutoScaling::AutoScalingGroup] Resource creation cancelled
.++++bundler: failed to load command: ./bin/cuffsert (./bin/cuffsert)
RuntimeError: Ye olde should-not-occur error
  path/to/cuffsert/lib/cuffsert/presenters.rb:145:in `resource'
  path/to/cuffsert/lib/cuffsert/presenters.rb:82:in `block in on_stack_event'
  path/to/cuffsert/lib/cuffsert/presenters.rb:82:in `each'
  path/to/cuffsert/lib/cuffsert/presenters.rb:82:in `on_stack_event'
  path/to/cuffsert/lib/cuffsert/presenters.rb:65:in `on_event'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/auto_detach_observer.rb:13:in `on_next_core'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/auto_detach_observer.rb:13:in `on_next_core'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/standard_query_operators.rb:266:in `block (3 levels) in select_with_index'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/auto_detach_observer.rb:13:in `on_next_core'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observer.rb:90:in `on_next'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:29:in `block (2 levels) in create_stack'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:84:in `block (3 levels) in stack_events'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:82:in `each'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:82:in `block (2 levels) in stack_events'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.6.42/lib/aws-sdk-core/pageable_response.rb:75:in `each'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:81:in `block in stack_events'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:80:in `loop'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:80:in `stack_events'
  path/to/cuffsert/lib/cuffsert/rxcfclient.rb:28:in `block in create_stack'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/creation.rb:19:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/creation.rb:19:in `block in create'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:99:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:99:in `subscribe_core'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:45:in `_subscribe'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:22:in `subscribe'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/standard_query_operators.rb:273:in `block in select_with_index'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:99:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:99:in `subscribe_core'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:45:in `_subscribe'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:22:in `subscribe'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/multiple.rb:598:in `block (3 levels) in concat'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/async_lock.rb:40:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/async_lock.rb:40:in `block in wait'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/async_lock.rb:27:in `loop'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/async_lock.rb:27:in `wait'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/operators/multiple.rb:561:in `block (2 levels) in concat'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:36:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:36:in `block in schedule_recursive'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:96:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:96:in `block in invoke_recursive'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:122:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduler.rb:122:in `invoke_recursive'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduled_item.rb:29:in `call'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/scheduled_item.rb:29:in `invoke'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/current_thread_scheduler.rb:67:in `run_trampoline'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/current_thread_scheduler.rb:40:in `schedule_relative_with_state'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/concurrency/local_scheduler.rb:20:in `schedule_with_state'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:42:in `_subscribe'
  path/to/cuffsert/vendor/bundle/ruby/2.0.0/gems/rx-0.0.3/lib/rx/core/observable.rb:24:in `subscribe'
  path/to/cuffsert/lib/cuffsert/presenters.rb:24:in `initialize'
  path/to/cuffsert/lib/cuffsert/presenters.rb:59:in `initialize'
  path/to/cuffsert/lib/cuffsert/main.rb:102:in `new'
  path/to/cuffsert/lib/cuffsert/main.rb:102:in `run'
  path/to/cuffsert/bin/cuffsert:5:in `<top (required)>'
```

**Comment by bittrance** [comment]
Double badness, I think. RendererPresenter has let through a resource with an unexpected :states value to ProgressbarRenderer.  The (admittedly hardcoded) timeout in cfarguments.rb is 5 minutes. Did it really take more than that to create the stack? If not, there is something unexpected about that stack event. Can you pull master and re-run? There should be some useful info in the error now.

**Comment by bittrance** [comment]
FWIW, here is one: RuntimeError: `Unexpected :states in {:stack_id=>"arn:aws:cloudformation:eu-west-1:456064453472:stack/parameters/4859a380-d856-11e6-bf4f-50faeb54d836", :event_id=>"DruidIngestCluster-CREATE_IN_PROGRESS-2017-01-11T23:33:02.292Z", :stack_name=>"parameters", :logical_resource_id=>"DruidIngestCluster", :physical_resource_id=>"", :resource_type=>"AWS::EMR::Cluster", :resource_status=>"CREATE_IN_PROGRESS", :resource_properties=>"{\"Instances\":{\"CoreInstanceGroup\":{\"InstanceCount\":\"2\",\"InstanceType\":\"m3.xlarge\"},\"Ec2KeyName\":\"bittrance\",\"MasterInstanceGroup\":{\"InstanceCount\":\"1\",\"InstanceType\":\"m3.xlarge\"}},\"ServiceRole\":\"EMR_DefaultRole\",\"LogUri\":\"s3://aws-logs-456064453472-eu-west-1/bittrance-druid-ingestion-test/\",\"JobFlowRole\":\"EMR_EC2_DefaultRole\",\"ReleaseLabel\":\"emr-5.2.1\",\"Tags\":[{\"Value\":\"bittrance-druid-ingestion-test\",\"Key\":\"Name\"},{\"Value\":\"staging\",\"Key\":\"Environment\"},{\"Value\":\"zauberer\",\"Key\":\"Role\"}],\"Name\":\"bittrance-druid-ingestion-test\"}\n", :states=>[:bad, :good, :progress]}`
